### PR TITLE
Add copyright notices

### PR DESCRIPTION
**Pull request by RedXanadu**
Add copyright notices to the .conf files, in line with the main CRS files.

### CODE REVIEW

**Comment by dune73** [comment]
Thank you @RedXanadu. Happy to merge this, but are you sure we need the Trustwave Copyright on the plugin? It's all our work.

**Comment by RedXanadu** [comment]
A question (sorry, it's a boring copyright question - these things are always so dull):

The Trustwave copyright notice covers 2006-2020. A lot of the plugins (e.g. most of the RE packages) started life in that time period, so because those plugins are based on (copy-pastes of) code from 2006-2020 they would need the Trustwave copyright line, right? Or not?

I think the options are:

1. Go through every plugin, find out if it uses code covered by the Trustwave period of copyright, and then choose an appropriate copyright notice (CRS only or CRS + Trustwave). So, we end up having different copyright messages in different plugins.
2. Have the same copyright notice on every plugin: CRS only.
3. Have the same copyright notice on every plugin: CRS + Trustwave (**currently, this is what I have done**).

I'm happy to go back through and implement options 1 or 2, if you think they're the right solution.

**Comment by dune73** [comment]
The first two rule exclusion plugins were released with CRS 3.0. Trustwave did not contribute to these rules, however.

Given we used the same TW copyright header for everything in 3.0, the TW copyright header was also used on said rules files.

Personally, I think we can simply change that and adopt proposal 2, also because the plugins are a new release with reworked rules. 

But a very conservative approach would be to keep the TW copyright intact, thus number 3.

What I would not do is using approach 1, since that is a lot of work and little benefit.

**Comment by RedXanadu** [comment]
Sounds reasonable.

Have implemented the 'CRS only' option to all plugins (or opened PRs where I can't merge by myself).

**Comment by dune73** [comment]
Thank you very much.

**Pull request merged**
